# Generated by Django 5.2.5 on 2026-09-21 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='dată (locală)')),
                ('completed_count', models.PositiveSmallIntegerField(default=0, verbose_name='exerciții finalizate')),
                ('goal', models.PositiveSmallIntegerField(default=10, verbose_name='obiectiv')),
                ('goal_reached_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zi de practică',
                'verbose_name_plural': 'zile de practică',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_day')],
            },
        ),
        migrations.CreateModel(
            name='PatternMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.PositiveSmallIntegerField(default=0)),
                ('exposures', models.PositiveIntegerField(default=0, verbose_name='expuneri')),
                ('misses', models.PositiveIntegerField(default=0, verbose_name='ratări')),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery', to='listening.speechpattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stăpânire tipar',
                'verbose_name_plural': 'stăpânire tipare',
                'ordering': ['user', 'mastery'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pattern'), name='unique_user_pattern'), models.CheckConstraint(condition=models.Q(('mastery__lte', 100)), name='mastery_range')],
            },
        ),
    ]
