# Generated by Django 5.2.5 on 2026-09-21 10:18

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verificat')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilizator',
                'verbose_name_plural': 'utilizatori',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('Europe/London', 'Regatul Unit (Londra)'), ('Europe/Dublin', 'Irlanda (Dublin)'), ('Europe/Bucharest', 'România (București)'), ('Europe/Chisinau', 'Moldova (Chișinău)'), ('Europe/Madrid', 'Spania (Madrid)'), ('Europe/Rome', 'Italia (Roma)'), ('Europe/Paris', 'Franța (Paris)'), ('Europe/Berlin', 'Germania (Berlin)'), ('America/New_York', 'SUA (New York)'), ('America/Toronto', 'Canada (Toronto)'), ('Australia/Sydney', 'Australia (Sydney)'), ('UTC', 'UTC')], default='Europe/London', max_length=64, verbose_name='fus orar')),
                ('daily_goal', models.PositiveSmallIntegerField(default=10, verbose_name='obiectiv zilnic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_accent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listening.accent', verbose_name='accent preferat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profiluri',
            },
        ),
    ]
