# Generated by Django 5.2.5 on 2026-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_voice',
            field=models.CharField(choices=[('marin', 'Marin'), ('ballad', 'Ballad'), ('cedar', 'Cedar')], default='marin', help_text='Alege vocea britanică pe care vrei să o auzi în exerciții.', max_length=20, verbose_name='vocea exercițiilor'),
        ),
    ]
