# Generated by Django 5.2.5 on 2026-09-21 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='nume')),
                ('tagline', models.CharField(blank=True, max_length=140, verbose_name='descriere scurtă')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preț lunar (GBP)')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('daily_exercise_limit', models.PositiveSmallIntegerField(blank=True, help_text='Gol = nelimitat.', null=True, verbose_name='limită exerciții/zi')),
                ('natural_level', models.BooleanField(default=False, verbose_name='Engleză naturală')),
                ('fast_level', models.BooleanField(default=False, verbose_name='Engleză rapidă')),
                ('full_mistake_history', models.BooleanField(default=False, verbose_name='istoric complet greșeli')),
                ('personalized_training', models.BooleanField(default=False, verbose_name='antrenament personalizat')),
                ('advanced_progress', models.BooleanField(default=False, verbose_name='progres avansat')),
                ('features_ro', models.TextField(blank=True, verbose_name='beneficii (câte unul pe rând)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planuri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('trialing', 'Perioadă de probă'), ('past_due', 'Plată restantă'), ('canceled', 'Anulat')], default='active', max_length=20)),
                ('provider', models.CharField(default='manual', max_length=20)),
                ('provider_customer_id', models.CharField(blank=True, max_length=100)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonament',
                'verbose_name_plural': 'abonamente',
            },
        ),
    ]
