"""Seed content: natural British English phrases with listening notes (Romanian)."""

# Each pattern dict:
#   pattern              - phenomenon slug
#   fragment             - contiguous words from `text` where it occurs
#   sounds_like          - IPA between slashes, an established informal spelling
#                          (gonna, d'you, lemme, dunno) or ""
#   ro_approximation     - rough Romanian-ear approximation (not phonetics) or ""
#   expected_from_level  - slowest level (clear / natural / fast) at which a native
#                          speaker would normally produce the phenomenon
#   explanation_ro       - short, hedged Romanian explanation of the general tendency

PHRASES: list[dict] = [
    # ------------------------------------------------------------------ everyday
    {
        "text": "Would you like me to pick you up after work?",
        "translation_ro": "Vrei să te iau (cu mașina) după muncă?",
        "topic": "everyday",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Would you",
                "sounds_like": "/wʊdʒu/",
                "ro_approximation": "uugiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar „would you” sună aproape ca un singur cuvânt.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” neaccentuat se rostește de obicei în forma slabă /tə/, cu o vocală scurtă și neutră.",
            },
            {
                "pattern": "linking",
                "fragment": "pick you up",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "Cuvintele se leagă de obicei fără pauză, iar „you” se lipește de vocala din „up”: „pick you‿up”.",
            },
        ],
    },
    {
        "text": "I'll sort it out later.",
        "translation_ro": "Rezolv mai târziu.",
        "topic": "everyday",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "I'll",
                "sounds_like": "/aɪl/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„I will” se contractă de obicei la „I'll”, iar /l/ final poate fi foarte slab, așa că se confundă ușor cu „I”.",
            },
            {
                "pattern": "linking",
                "fragment": "sort it out",
                "sounds_like": "",
                "ro_approximation": "sor-ti-taut",
                "expected_from_level": "clear",
                "explanation_ro": "Consoanele finale se leagă de vocalele următoare, așa că „sort‿it‿out” curge adesea ca un singur bloc.",
            },
        ],
    },
    {
        "text": "I might pop in on the way home.",
        "translation_ro": "S-ar putea să trec pe acolo în drum spre casă.",
        "topic": "everyday",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "might",
                "sounds_like": "/maɪʔ/",
                "ro_approximation": "mai'",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „might” poate deveni o oprire glotală înaintea unei consoane.",
            },
            {
                "pattern": "linking",
                "fragment": "pop in on",
                "sounds_like": "",
                "ro_approximation": "po-pi-non",
                "expected_from_level": "clear",
                "explanation_ro": "/p/ și /n/ se leagă de obicei de vocalele următoare, așa că „pop‿in‿on” poate suna ca un singur cuvânt.",
            },
        ],
    },
    {
        "text": "Can you put the kettle on?",
        "translation_ro": "Poți să pui de-un ceai (să fierbi apa)?",
        "topic": "everyday",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Can",
                "sounds_like": "/kən/",
                "ro_approximation": "căn",
                "expected_from_level": "clear",
                "explanation_ro": "În întrebări, „can” e de obicei neaccentuat și se rostește în forma slabă /kən/.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "put the",
                "sounds_like": "/pʊʔ ðə/",
                "ro_approximation": "pu' dă",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „put” poate fi înlocuit de o oprire glotală înainte de „the”.",
            },
        ],
    },
    {
        "text": "I'm just going to nip to the shop.",
        "translation_ro": "Dau o fugă până la magazin.",
        "topic": "everyday",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "just",
                "sounds_like": "/dʒʌs/",
                "ro_approximation": "giăs",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ din „just” cade adesea înaintea altei consoane.",
            },
            {
                "pattern": "everyday-reduction",
                "fragment": "going to",
                "sounds_like": "gonna",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea obișnuită, „going to” cu sens de viitor se reduce adesea la „gonna”.",
            },
        ],
    },
    {
        "text": "Could you turn the telly down a bit?",
        "translation_ro": "Poți să dai televizorul puțin mai încet?",
        "topic": "everyday",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Could you",
                "sounds_like": "/kʊdʒu/",
                "ro_approximation": "cugiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar „could you” sună ca un singur cuvânt.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "a bit",
                "sounds_like": "/ə bɪʔ/",
                "ro_approximation": "ă bi'",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ final din „bit” e adesea doar o oprire glotală, mai ales la final de propoziție.",
            },
        ],
    },
    {
        "text": "Just leave them by the door, I'll deal with them later.",
        "translation_ro": "Lasă-le lângă ușă, mă ocup de ele mai târziu.",
        "topic": "everyday",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "them",
                "sounds_like": "/ðəm/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„them” neaccentuat are de obicei forma slabă /ðəm/; în vorbirea rapidă poate ajunge /əm/, ca „'em”.",
            },
            {
                "pattern": "contraction",
                "fragment": "I'll",
                "sounds_like": "/aɪl/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„I will” apare de obicei contras ca „I'll”, lipit de verbul următor; /l/ poate fi abia perceptibil.",
            },
        ],
    },
    # ---------------------------------------------------------------------- work
    {
        "text": "Did you get a chance to look at it?",
        "translation_ro": "Ai apucat să te uiți pe el?",
        "topic": "work",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Did you",
                "sounds_like": "/dɪdʒu/",
                "ro_approximation": "digiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar cele două cuvinte sună ca unul singur.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "get a",
                "sounds_like": "/ɡeʔ ə/",
                "ro_approximation": "ghe'ă",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „get” poate deveni o oprire glotală înaintea unei vocale, iar „a” se lipește de el.",
            },
            {
                "pattern": "linking",
                "fragment": "look at it",
                "sounds_like": "/lʊk ət ɪt/",
                "ro_approximation": "lu-că-tit",
                "expected_from_level": "clear",
                "explanation_ro": "„look‿at‿it” se leagă de obicei într-un singur bloc, iar „at” neaccentuat are adesea forma slabă /ət/.",
            },
        ],
    },
    {
        "text": "Have you got a minute?",
        "translation_ro": "Ai un minut?",
        "topic": "work",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Have you",
                "sounds_like": "/həv jə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "La început de întrebare, „have” e de obicei slab (/həv/, uneori /əv/), iar „you” poate deveni /jə/.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "got a",
                "sounds_like": "/ɡɒʔ ə/",
                "ro_approximation": "go'a",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „got” poate deveni o oprire glotală înaintea unei vocale.",
            },
        ],
    },
    {
        "text": "Can we push the meeting back to Thursday?",
        "translation_ro": "Putem amâna ședința pe joi?",
        "topic": "work",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Can",
                "sounds_like": "/kən/",
                "ro_approximation": "căn",
                "expected_from_level": "clear",
                "explanation_ro": "„can” neaccentuat se reduce de obicei la forma slabă /kən/, cu accentul pe „push”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” are de obicei forma slabă /tə/ și se pierde ușor între „back” și „Thursday”.",
            },
        ],
    },
    {
        "text": "I'll send it over first thing tomorrow.",
        "translation_ro": "Ți-l trimit mâine la prima oră.",
        "topic": "work",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "linking",
                "fragment": "send it over",
                "sounds_like": "",
                "ro_approximation": "sen-di-tou-vă",
                "expected_from_level": "clear",
                "explanation_ro": "„send‿it‿over” curge de obicei legat, iar „it” neaccentuat e doar un /ɪ/ scurt între consoane.",
            },
            {
                "pattern": "elision",
                "fragment": "first thing",
                "sounds_like": "/fɜːs θɪŋ/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ din „first” cade adesea între /s/ și „th”, deci se aude ceva ca „firs' thing”.",
            },
        ],
    },
    {
        "text": "Sorry, I'm running a bit late this morning.",
        "translation_ro": "Scuze, am o mică întârziere în dimineața asta.",
        "topic": "work",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "linking",
                "fragment": "running a",
                "sounds_like": "",
                "ro_approximation": "raninga",
                "expected_from_level": "clear",
                "explanation_ro": "Articolul „a” se lipește de obicei de „running”, așa că cele două pot suna ca un singur cuvânt.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "bit late",
                "sounds_like": "/bɪʔ leɪt/",
                "ro_approximation": "bi' leit",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „bit” poate deveni o oprire glotală înaintea lui /l/.",
            },
        ],
    },
    {
        "text": "Could you cover my shift on Saturday?",
        "translation_ro": "Poți să-mi acoperi tura de sâmbătă?",
        "topic": "work",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Could you",
                "sounds_like": "/kʊdʒu/",
                "ro_approximation": "cugiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, deci „could you” poate suna ca un singur cuvânt.",
            },
            {
                "pattern": "schwa",
                "fragment": "Saturday",
                "sounds_like": "/ˈsætədeɪ/",
                "ro_approximation": "setădei",
                "expected_from_level": "clear",
                "explanation_ro": "În engleza britanică, silaba din mijloc e de obicei un schwa scurt /ə/, fără „r” pronunțat.",
            },
        ],
    },
    {
        "text": "We should have finished it by now.",
        "translation_ro": "Ar fi trebuit să-l fi terminat până acum.",
        "topic": "work",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "should have",
                "sounds_like": "/ʃʊd əv/",
                "ro_approximation": "șudăv",
                "expected_from_level": "clear",
                "explanation_ro": "După „should”, „have” are de obicei forma slabă /əv/ – de aici greșeala de scriere „should of”.",
            },
            {
                "pattern": "linking",
                "fragment": "finished it",
                "sounds_like": "/ˈfɪnɪʃt ɪt/",
                "ro_approximation": "finiș-tit",
                "expected_from_level": "clear",
                "explanation_ro": "Terminația „-ed” se pronunță aici /t/ și se leagă de obicei de „it”, fără pauză.",
            },
        ],
    },
    # ------------------------------------------------------------------ shopping
    {
        "text": "Do you need a bag?",
        "translation_ro": "Aveți nevoie de o pungă?",
        "topic": "shopping",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "Do you",
                "sounds_like": "d'you",
                "ro_approximation": "diu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea rapidă de zi cu zi, „do you” se reduce adesea la „d'you” (/djə/), aproape o singură silabă.",
            },
            {
                "pattern": "linking",
                "fragment": "need a",
                "sounds_like": "",
                "ro_approximation": "ni-dă",
                "expected_from_level": "clear",
                "explanation_ro": "/d/ final din „need” se leagă de obicei de „a”: „need‿a bag”.",
            },
        ],
    },
    {
        "text": "That's ten pounds fifty, please.",
        "translation_ro": "Face zece lire și cincizeci, vă rog.",
        "topic": "shopping",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "ten pounds",
                "sounds_like": "/tem paʊndz/",
                "ro_approximation": "tem paunz",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /n/ din „ten” se apropie adesea de /m/ înaintea lui /p/.",
            },
            {
                "pattern": "contraction",
                "fragment": "That's",
                "sounds_like": "/ðæts/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„That is” se contractă de obicei la „that's”, iar /s/ final se leagă de cuvântul următor.",
            },
        ],
    },
    {
        "text": "Can I pay by card?",
        "translation_ro": "Pot plăti cu cardul?",
        "topic": "shopping",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Can",
                "sounds_like": "/kən/",
                "ro_approximation": "că-nai",
                "expected_from_level": "clear",
                "explanation_ro": "„can” neaccentuat are de obicei forma slabă /kən/ și se leagă de „I”, ca o singură silabă scurtă.",
            },
        ],
    },
    {
        "text": "Have you got this in a smaller size?",
        "translation_ro": "Aveți asta și într-o mărime mai mică?",
        "topic": "shopping",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "got this",
                "sounds_like": "/ɡɒʔ ðɪs/",
                "ro_approximation": "go' dis",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „got” poate deveni o oprire glotală înainte de „this”.",
            },
            {
                "pattern": "linking",
                "fragment": "in a",
                "sounds_like": "/ɪn ə/",
                "ro_approximation": "ină",
                "expected_from_level": "clear",
                "explanation_ro": "/n/ se leagă de obicei de „a”, iar „in‿a” sună ca o singură silabă scurtă.",
            },
        ],
    },
    {
        "text": "Are you after anything in particular?",
        "translation_ro": "Căutați ceva anume?",
        "topic": "shopping",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "reduced-function-word",
                "fragment": "Are you",
                "sounds_like": "/ə jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "La început de întrebare, „are you” poate fi foarte redus în vorbirea curentă (/ə jə/), aproape înghițit.",
            },
            {
                "pattern": "linking-r",
                "fragment": "after anything",
                "sounds_like": "/ˈɑːftər ˈeniθɪŋ/",
                "ro_approximation": "aftă-renifing",
                "expected_from_level": "clear",
                "explanation_ro": "În engleza britanică, „r” din „after” de obicei nu se aude, dar reapare adesea înaintea unei vocale.",
            },
            {
                "pattern": "schwa",
                "fragment": "particular",
                "sounds_like": "/pəˈtɪkjələ/",
                "ro_approximation": "pă-ti-kiu-lă",
                "expected_from_level": "clear",
                "explanation_ro": "Doar silaba „ti” e accentuată; celelalte au de obicei vocale reduse la schwa /ə/.",
            },
        ],
    },
    {
        "text": "Do you want a receipt?",
        "translation_ro": "Doriți bonul?",
        "topic": "shopping",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "Do you want a",
                "sounds_like": "d'you wanna",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea rapidă, începutul se poate comprima în „d'you wanna”, iar „receipt” rămâne cuvântul cel mai clar.",
            },
        ],
    },
    # --------------------------------------------------------------- phone-calls
    {
        "text": "I was going to give you a ring later.",
        "translation_ro": "Voiam să-ți dau un telefon mai târziu.",
        "topic": "phone-calls",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "was",
                "sounds_like": "/wəz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„was” neaccentuat are de obicei forma slabă /wəz/, un sunet scurt și ușor de ratat.",
            },
            {
                "pattern": "everyday-reduction",
                "fragment": "going to",
                "sounds_like": "gonna",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea obișnuită, „was going to” (aveam de gând să) devine adesea „was gonna”.",
            },
            {
                "pattern": "linking",
                "fragment": "give you a",
                "sounds_like": "",
                "ro_approximation": "ghiv-iu-ă",
                "expected_from_level": "clear",
                "explanation_ro": "„give you a” curge de obicei legat, iar „you” și „a” neaccentuate sunt foarte scurte.",
            },
        ],
    },
    {
        "text": "Can I just take your name, please?",
        "translation_ro": "Îmi puteți spune numele, vă rog?",
        "topic": "phone-calls",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "just take",
                "sounds_like": "/dʒʌs teɪk/",
                "ro_approximation": "giăs teik",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ final din „just” cade adesea înaintea lui „take”, deci se aude un singur /t/.",
            },
            {
                "pattern": "reduced-function-word",
                "fragment": "your",
                "sounds_like": "/jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "„your” neaccentuat se poate reduce la /jə/ în vorbirea curentă, ușor de confundat cu „you” sau „a”.",
            },
        ],
    },
    {
        "text": "Sorry, you're breaking up a bit.",
        "translation_ro": "Scuze, nu te aud bine (se întrerupe).",
        "topic": "phone-calls",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "you're",
                "sounds_like": "/jɔː/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„you are” se contractă de obicei la „you're” (/jɔː/ sau /jə/), care poate suna identic cu „your”.",
            },
            {
                "pattern": "linking",
                "fragment": "breaking up a",
                "sounds_like": "",
                "ro_approximation": "breikin-ga-pă",
                "expected_from_level": "clear",
                "explanation_ro": "„breaking‿up‿a” se leagă de obicei, fără granițe clare între cuvinte.",
            },
        ],
    },
    {
        "text": "Could I speak to someone about my bill?",
        "translation_ro": "Aș putea vorbi cu cineva despre factura mea?",
        "topic": "phone-calls",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” are de obicei forma slabă /tə/ și se lipește de „someone”.",
            },
            {
                "pattern": "linking",
                "fragment": "someone about",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "/n/ final din „someone” se leagă de obicei de vocala din „about”, fără pauză.",
            },
        ],
    },
    {
        "text": "I'm afraid she's not in at the moment.",
        "translation_ro": "Din păcate nu e aici momentan.",
        "topic": "phone-calls",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "she's",
                "sounds_like": "/ʃiːz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„she is” se contractă de obicei la „she's” și se leagă strâns de „not”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "at",
                "sounds_like": "/ət/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„at” neaccentuat are de obicei forma slabă /ət/, greu de observat între „in” și „the moment”.",
            },
        ],
    },
    {
        "text": "Can you hold on for a second?",
        "translation_ro": "Puteți să așteptați o secundă?",
        "topic": "phone-calls",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "linking",
                "fragment": "hold on",
                "sounds_like": "",
                "ro_approximation": "hol-don",
                "expected_from_level": "clear",
                "explanation_ro": "/d/ final din „hold” se leagă de obicei de vocala din „on”: „hold‿on”.",
            },
            {
                "pattern": "linking-r",
                "fragment": "for a",
                "sounds_like": "/fər ə/",
                "ro_approximation": "fă-ră",
                "expected_from_level": "clear",
                "explanation_ro": "În engleza britanică, „r” din „for” se aude de obicei doar când urmează o vocală, ca aici înainte de „a”.",
            },
        ],
    },
    {
        "text": "I'll get back to you as soon as I can.",
        "translation_ro": "Revin cu un răspuns cât de repede pot.",
        "topic": "phone-calls",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "get back",
                "sounds_like": "/ɡeʔ bæk/",
                "ro_approximation": "ghe' bec",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „get” poate deveni o oprire glotală înaintea lui /b/.",
            },
            {
                "pattern": "weak-form",
                "fragment": "as soon as",
                "sounds_like": "/əz suːn əz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "Ambele „as” au de obicei forma slabă /əz/, așa că „soon” rămâne cuvântul cel mai clar.",
            },
        ],
    },
    {
        "text": "Can you tell him I called?",
        "translation_ro": "Poți să-i spui că am sunat?",
        "topic": "phone-calls",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "dropped-consonant",
                "fragment": "him",
                "sounds_like": "/ɪm/",
                "ro_approximation": "telim",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „h” din „him” neaccentuat cade adesea, iar „tell him” se leagă ca un singur cuvânt.",
            },
        ],
    },
    # ----------------------------------------------------------------- transport
    {
        "text": "Mind the gap.",
        "translation_ro": "Atenție la spațiul dintre peron și tren.",
        "topic": "transport",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "Mind the",
                "sounds_like": "/maɪn ðə/",
                "ro_approximation": "main' dă",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /d/ din „mind” cade adesea între /n/ și „the”.",
            },
        ],
    },
    {
        "text": "Does this bus go to the station?",
        "translation_ro": "Autobuzul ăsta merge la gară?",
        "topic": "transport",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Does",
                "sounds_like": "/dəz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "La început de întrebare, „does” e de obicei neaccentuat și are forma slabă /dəz/.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” are de obicei forma slabă /tə/ și se pierde ușor înainte de „the station”.",
            },
        ],
    },
    {
        "text": "The next train is delayed by ten minutes.",
        "translation_ro": "Următorul tren are o întârziere de zece minute.",
        "topic": "transport",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "next train",
                "sounds_like": "/neks treɪn/",
                "ro_approximation": "nex trein",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ din „next” cade adesea între /s/ și /t/ din „train”.",
            },
            {
                "pattern": "assimilation",
                "fragment": "ten minutes",
                "sounds_like": "/tem ˈmɪnɪts/",
                "ro_approximation": "tem-minits",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /n/ din „ten” devine adesea /m/ înaintea lui /m/, iar cele două se contopesc.",
            },
        ],
    },
    {
        "text": "Is this the right stop for the hospital?",
        "translation_ro": "Asta e stația bună pentru spital?",
        "topic": "transport",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "right stop",
                "sounds_like": "/raɪʔ stɒp/",
                "ro_approximation": "rai' stop",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „right” poate deveni o oprire glotală înaintea lui /s/.",
            },
            {
                "pattern": "weak-form",
                "fragment": "for",
                "sounds_like": "/fə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„for” neaccentuat are de obicei forma slabă /fə/, ușor de confundat cu „a” sau „to”.",
            },
        ],
    },
    {
        "text": "Are you getting off at the next stop?",
        "translation_ro": "Coborâți la stația următoare?",
        "topic": "transport",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "reduced-function-word",
                "fragment": "Are you",
                "sounds_like": "/ə jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „are you” poate fi foarte redus, așa că întrebarea pare să înceapă cu „getting off”.",
            },
            {
                "pattern": "linking",
                "fragment": "getting off at",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„getting‿off‿at” se leagă de obicei într-un bloc, iar „at” neaccentuat are adesea forma slabă /ət/.",
            },
            {
                "pattern": "elision",
                "fragment": "next stop",
                "sounds_like": "/neks stɒp/",
                "ro_approximation": "nex stop",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ din „next” cade adesea între două sunete /s/.",
            },
        ],
    },
    {
        "text": "Stand clear of the closing doors, please.",
        "translation_ro": "Îndepărtați-vă de ușile care se închid, vă rog.",
        "topic": "transport",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "linking-r",
                "fragment": "clear of",
                "sounds_like": "/klɪər əv/",
                "ro_approximation": "cli-răv",
                "expected_from_level": "clear",
                "explanation_ro": "În engleza britanică, „r” din „clear” se aude de obicei doar pentru că urmează o vocală, aici „of”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "of",
                "sounds_like": "/əv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„of” neaccentuat are de obicei forma slabă /əv/, lipită de cuvântul dinainte.",
            },
        ],
    },
    {
        "text": "Where are you off to?",
        "translation_ro": "Unde mergi?",
        "topic": "transport",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "linking-r",
                "fragment": "Where are",
                "sounds_like": "/weər ə/",
                "ro_approximation": "ue-ră",
                "expected_from_level": "clear",
                "explanation_ro": "„r” din „where” reapare de obicei înainte de „are”, iar „are” neaccentuat se reduce adesea la /ə/.",
            },
            {
                "pattern": "linking",
                "fragment": "you off",
                "sounds_like": "",
                "ro_approximation": "iu-uof",
                "expected_from_level": "clear",
                "explanation_ro": "Între „you” și „off” apare de obicei un /w/ scurt de legătură, așa că cele două curg împreună.",
            },
        ],
    },
    {
        "text": "Is it far away from the station?",
        "translation_ro": "E departe de gară?",
        "topic": "transport",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "linking-r",
                "fragment": "far away",
                "sounds_like": "/fɑːr əˈweɪ/",
                "ro_approximation": "fa-răuei",
                "expected_from_level": "clear",
                "explanation_ro": "În engleza britanică, „r” din „far” de obicei nu se aude, dar reapare adesea înainte de „away”.",
            },
            {
                "pattern": "linking",
                "fragment": "Is it",
                "sounds_like": "",
                "ro_approximation": "izit",
                "expected_from_level": "clear",
                "explanation_ro": "/z/ din „is” se leagă de obicei de „it”, iar cele două sună ca un singur cuvânt scurt.",
            },
        ],
    },
    # ---------------------------------------------------------------- healthcare
    {
        "text": "I'd like to book an appointment with a GP.",
        "translation_ro": "Aș vrea să fac o programare la medicul de familie.",
        "topic": "healthcare",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "I'd",
                "sounds_like": "/aɪd/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„I would” se contractă de obicei la „I'd”, iar /d/ poate fi foarte slab înainte de „like”.",
            },
            {
                "pattern": "linking",
                "fragment": "book an appointment",
                "sounds_like": "",
                "ro_approximation": "bu-că-năpointmănt",
                "expected_from_level": "clear",
                "explanation_ro": "Consoanele finale se leagă de obicei de vocalele următoare, așa că „book‿an‿appointment” curge legat.",
            },
        ],
    },
    {
        "text": "How long have you had the cough?",
        "translation_ro": "De cât timp aveți tusea?",
        "topic": "healthcare",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "have you",
                "sounds_like": "/əv jə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "În mijlocul întrebării, „have” neaccentuat își pierde adesea „h”-ul și devine /əv/.",
            },
        ],
    },
    {
        "text": "Take two of these twice a day after food.",
        "translation_ro": "Luați câte două de două ori pe zi, după masă.",
        "topic": "healthcare",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "of",
                "sounds_like": "/əv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„of” are de obicei forma slabă /əv/; în vorbirea rapidă /v/ poate dispărea înainte de „these”.",
            },
            {
                "pattern": "linking",
                "fragment": "twice a day",
                "sounds_like": "",
                "ro_approximation": "tuai-să dei",
                "expected_from_level": "clear",
                "explanation_ro": "/s/ din „twice” se leagă de obicei de „a”, așa că „twice‿a day” curge fără pauză.",
            },
        ],
    },
    {
        "text": "Is it painful when I press here?",
        "translation_ro": "Vă doare când apăs aici?",
        "topic": "healthcare",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "linking",
                "fragment": "when I",
                "sounds_like": "",
                "ro_approximation": "ue-nai",
                "expected_from_level": "clear",
                "explanation_ro": "/n/ din „when” se leagă de obicei de „I”, fără pauză între cuvinte.",
            },
        ],
    },
    {
        "text": "You'll need to get a prescription from the pharmacy.",
        "translation_ro": "Va trebui să luați o rețetă de la farmacie.",
        "topic": "healthcare",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "You'll",
                "sounds_like": "/juːl/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„you will” se contractă de obicei la „you'll”, ușor de confundat cu simplul „you”.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "get a",
                "sounds_like": "/ɡeʔ ə/",
                "ro_approximation": "ghe'ă",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „get” poate deveni o oprire glotală înaintea vocalei din „a”.",
            },
        ],
    },
    {
        "text": "Can you confirm your date of birth for me?",
        "translation_ro": "Îmi puteți confirma data nașterii?",
        "topic": "healthcare",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "reduced-function-word",
                "fragment": "your",
                "sounds_like": "/jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „your” neaccentuat se poate reduce la /jə/, greu de observat între „confirm” și „date”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "of",
                "sounds_like": "/əv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„of” are de obicei forma slabă /əv/, iar „date of birth” se rostește ca o singură expresie.",
            },
        ],
    },
    {
        "text": "There's no need to worry, it's quite common.",
        "translation_ro": "Nu e cazul să vă îngrijorați, e destul de frecvent.",
        "topic": "healthcare",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "There's",
                "sounds_like": "/ðeəz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„there is” se contractă de obicei la „there's”, rostit scurt, adesea /ðəz/ când e neaccentuat.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "quite common",
                "sounds_like": "/kwaɪʔ ˈkɒmən/",
                "ro_approximation": "cuai' comăn",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „quite” poate fi înlocuit de o oprire glotală înaintea lui /k/.",
            },
        ],
    },
    # -------------------------------------------------------------------- school
    {
        "text": "What time's pick-up today?",
        "translation_ro": "La ce oră îi luăm (pe copii) azi?",
        "topic": "school",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "What",
                "sounds_like": "/wɒʔ/",
                "ro_approximation": "uo'",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „what” poate deveni o oprire glotală înainte de „time”.",
            },
            {
                "pattern": "contraction",
                "fragment": "time's",
                "sounds_like": "/taɪmz/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„time is” se contractă de obicei la „time's”, iar „is” rămâne doar un /z/ lipit de cuvânt.",
            },
        ],
    },
    {
        "text": "Don't forget your PE kit tomorrow.",
        "translation_ro": "Nu uita echipamentul de sport mâine.",
        "topic": "school",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "Don't forget",
                "sounds_like": "/dəʊn fəˈɡet/",
                "ro_approximation": "doun' făghet",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /t/ din „don't” cade adesea înaintea lui /f/.",
            },
            {
                "pattern": "schwa",
                "fragment": "tomorrow",
                "sounds_like": "/təˈmɒrəʊ/",
                "ro_approximation": "tă-MO-rou",
                "expected_from_level": "clear",
                "explanation_ro": "Prima silabă are de obicei un schwa scurt (/tə/), nu „tu”, iar accentul cade pe „-mor-”.",
            },
        ],
    },
    {
        "text": "She's got a bit of a cough, so she's off today.",
        "translation_ro": "Tușește puțin, așa că azi stă acasă.",
        "topic": "school",
        "difficulty": 5,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "got a bit of a",
                "sounds_like": "/ɡɒʔ ə bɪʔ əv ə/",
                "ro_approximation": "go'a bi'ova",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, ambele /t/ pot deveni opriri glotale înaintea vocalelor, iar totul se leagă.",
            },
            {
                "pattern": "weak-form",
                "fragment": "of",
                "sounds_like": "/əv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„of” are de obicei forma slabă /əv/, lipită de „bit” și „a”; în vorbirea rapidă poate ajunge /ə/.",
            },
        ],
    },
    {
        "text": "Could you sign the permission slip for the school trip?",
        "translation_ro": "Puteți semna acordul pentru excursia școlară?",
        "topic": "school",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Could you",
                "sounds_like": "/kʊdʒu/",
                "ro_approximation": "cugiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar „could you” sună ca un singur cuvânt.",
            },
            {
                "pattern": "schwa",
                "fragment": "permission",
                "sounds_like": "/pəˈmɪʃn̩/",
                "ro_approximation": "pă-MI-șn",
                "expected_from_level": "clear",
                "explanation_ro": "„per-” și „-sion” sunt neaccentuate și au de obicei vocale reduse, așa că se aude mai ales „-MI-”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "for",
                "sounds_like": "/fə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„for” neaccentuat are de obicei forma slabă /fə/ și se pierde ușor înainte de „the school trip”.",
            },
        ],
    },
    {
        "text": "Has he handed in his homework yet?",
        "translation_ro": "Și-a predat tema?",
        "topic": "school",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "dropped-consonant",
                "fragment": "he",
                "sounds_like": "/i/",
                "ro_approximation": "hazi",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „h” din „he” neaccentuat cade adesea, iar „has he” se leagă într-un singur bloc.",
            },
            {
                "pattern": "dropped-consonant",
                "fragment": "his",
                "sounds_like": "/ɪz/",
                "ro_approximation": "i-niz",
                "expected_from_level": "natural",
                "explanation_ro": "„his” neaccentuat își pierde adesea „h”-ul și se leagă de „in”: „handed in‿his homework”.",
            },
        ],
    },
    {
        "text": "What did you get up to at school today?",
        "translation_ro": "Ce ai făcut azi la școală?",
        "topic": "school",
        "difficulty": 4,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "did you",
                "sounds_like": "/dɪdʒə/",
                "ro_approximation": "digiă",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „did you” devine adesea /dɪdʒə/ și se leagă de „what”, ca un singur bloc.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "get up",
                "sounds_like": "/ɡeʔ ʌp/",
                "ro_approximation": "ghe' ap",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „get” poate deveni o oprire glotală înaintea vocalei din „up”.",
            },
        ],
    },
    # ------------------------------------------------------------------- friends
    {
        "text": "Do you fancy grabbing a coffee?",
        "translation_ro": "Ai chef să bem o cafea?",
        "topic": "friends",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "Do you",
                "sounds_like": "d'you",
                "ro_approximation": "diu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea informală, „do you” se reduce adesea la „d'you” (/djə/), așa că „fancy” iese în evidență.",
            },
            {
                "pattern": "linking",
                "fragment": "grabbing a",
                "sounds_like": "",
                "ro_approximation": "grebinga",
                "expected_from_level": "clear",
                "explanation_ro": "Articolul „a” se lipește de obicei de „grabbing”, fără pauză.",
            },
        ],
    },
    {
        "text": "You could have told me earlier.",
        "translation_ro": "Puteai să-mi spui mai devreme.",
        "topic": "friends",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "could have",
                "sounds_like": "/kʊd əv/",
                "ro_approximation": "cudăv",
                "expected_from_level": "clear",
                "explanation_ro": "După „could”, „have” are de obicei forma slabă /əv/; în vorbirea rapidă poate suna ca „coulda”.",
            },
            {
                "pattern": "elision",
                "fragment": "told me",
                "sounds_like": "/təʊl mi/",
                "ro_approximation": "toul mi",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, /d/ din „told” cade adesea între /l/ și /m/.",
            },
        ],
    },
    {
        "text": "I didn't realise you were coming.",
        "translation_ro": "Nu mi-am dat seama că vii.",
        "topic": "friends",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "didn't",
                "sounds_like": "/ˈdɪdn̩(t)/",
                "ro_approximation": "didn'",
                "expected_from_level": "clear",
                "explanation_ro": "„did not” se contractă de obicei la „didn't”; înaintea unei consoane, /t/ final adesea abia se aude.",
            },
            {
                "pattern": "weak-form",
                "fragment": "were",
                "sounds_like": "/wə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„were” neaccentuat are de obicei forma slabă /wə/, ușor de confundat cu „was” sau „are”.",
            },
        ],
    },
    {
        "text": "Shall we head off?",
        "translation_ro": "Plecăm?",
        "topic": "friends",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Shall",
                "sounds_like": "/ʃəl/",
                "ro_approximation": "șăl",
                "expected_from_level": "clear",
                "explanation_ro": "„shall” neaccentuat are de obicei forma slabă /ʃəl/, cu o vocală foarte scurtă.",
            },
            {
                "pattern": "linking",
                "fragment": "head off",
                "sounds_like": "",
                "ro_approximation": "he-dof",
                "expected_from_level": "clear",
                "explanation_ro": "/d/ din „head” se leagă de obicei de vocala din „off”: „head‿off”.",
            },
        ],
    },
    {
        "text": "Are you coming to the pub later?",
        "translation_ro": "Vii la pub mai târziu?",
        "topic": "friends",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "reduced-function-word",
                "fragment": "Are you",
                "sounds_like": "/ə jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „are you” poate fi atât de slab încât întrebarea pare să înceapă cu „coming”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” are de obicei forma slabă /tə/ și se leagă de „the pub”.",
            },
        ],
    },
    {
        "text": "I'm absolutely knackered, I'm going to head home.",
        "translation_ro": "Sunt mort de oboseală, mă duc acasă.",
        "topic": "friends",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "I'm going to",
                "sounds_like": "I'm gonna",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea informală, „I'm going to” se reduce adesea la „I'm gonna”.",
            },
        ],
    },
    {
        "text": "Cheers for sorting that out.",
        "translation_ro": "Mersi că te-ai ocupat de asta.",
        "topic": "friends",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "for",
                "sounds_like": "/fə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„for” neaccentuat are de obicei forma slabă /fə/ și se lipește de „cheers”.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "that out",
                "sounds_like": "/ðæʔ aʊt/",
                "ro_approximation": "dă' aut",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „that” poate deveni o oprire glotală înaintea vocalei din „out”.",
            },
        ],
    },
    {
        "text": "I saw a mate of mine in town yesterday.",
        "translation_ro": "Am văzut ieri un prieten în oraș.",
        "topic": "friends",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "intrusive-r",
                "fragment": "saw a",
                "sounds_like": "/sɔːr ə/",
                "ro_approximation": "so-ră",
                "expected_from_level": "natural",
                "explanation_ro": "Mulți vorbitori britanici adaugă un „r” nescris între „saw” și „a”, pentru a lega cele două vocale.",
            },
            {
                "pattern": "weak-form",
                "fragment": "of",
                "sounds_like": "/əv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„of” are de obicei forma slabă /əv/ și se leagă de „mate”: „mate‿of mine”.",
            },
        ],
    },
    # ---------------------------------------------------------------- small-talk
    {
        "text": "Lovely weather we're having, isn't it?",
        "translation_ro": "Ce vreme frumoasă avem, nu?",
        "topic": "small-talk",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "we're",
                "sounds_like": "/wɪə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„we are” se contractă de obicei la „we're”, care poate suna aproape ca „we” sau „were”.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "isn't it",
                "sounds_like": "/ˈɪzn̩ ɪʔ/",
                "ro_approximation": "izn' i'",
                "expected_from_level": "natural",
                "explanation_ro": "În întrebarea de final, /t/ din „isn't” poate cădea, iar /t/ din „it” devine adesea o oprire glotală.",
            },
        ],
    },
    {
        "text": "It's absolutely chucking it down out there.",
        "translation_ro": "Plouă cu găleata afară.",
        "topic": "small-talk",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "linking",
                "fragment": "chucking it down",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„chucking‿it‿down” se leagă de obicei strâns, iar „it” neaccentuat e doar un /ɪ/ scurt.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "out there",
                "sounds_like": "/aʊʔ ðeə/",
                "ro_approximation": "au' dea",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „out” poate deveni o oprire glotală înainte de „there”.",
            },
        ],
    },
    {
        "text": "Did you have a good weekend?",
        "translation_ro": "Ai avut un weekend plăcut?",
        "topic": "small-talk",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "assimilation",
                "fragment": "Did you",
                "sounds_like": "/dɪdʒu/",
                "ro_approximation": "digiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar „did you” sună ca un singur cuvânt.",
            },
            {
                "pattern": "linking",
                "fragment": "have a",
                "sounds_like": "",
                "ro_approximation": "he-vă",
                "expected_from_level": "clear",
                "explanation_ro": "/v/ din „have” se leagă de obicei de „a”: „have‿a good weekend”.",
            },
        ],
    },
    {
        "text": "Not too bad, thanks. And you?",
        "translation_ro": "Nu prea rău, mersi. Tu?",
        "topic": "small-talk",
        "difficulty": 1,
        "patterns": [
            {
                "pattern": "glottal-t",
                "fragment": "Not too",
                "sounds_like": "/nɒʔ tuː/",
                "ro_approximation": "no' tu",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „not” poate deveni o oprire glotală înainte de „too”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "And",
                "sounds_like": "/ən/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„and” neaccentuat are de obicei forma slabă /ən/, adesea fără /d/.",
            },
        ],
    },
    {
        "text": "It's supposed to brighten up later.",
        "translation_ro": "Se zice că se înseninează mai târziu.",
        "topic": "small-talk",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "elision",
                "fragment": "supposed to",
                "sounds_like": "/səˈpəʊs tə/",
                "ro_approximation": "săpous tă",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea naturală, finalul lui „supposed” se contopește adesea cu /t/ din „to”, deci se aude un singur /t/.",
            },
            {
                "pattern": "schwa",
                "fragment": "supposed",
                "sounds_like": "/səˈpəʊzd/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "Prima silabă are de obicei un schwa foarte scurt; în vorbirea rapidă poate aproape dispărea: „s'posed”.",
            },
        ],
    },
    {
        "text": "Have you been anywhere nice for your holidays?",
        "translation_ro": "Ai fost undeva frumos în concediu?",
        "topic": "small-talk",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "weak-form",
                "fragment": "Have you",
                "sounds_like": "/əv jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „have you” e adesea slab și rapid, uneori /əv jə/, fără „h”.",
            },
            {
                "pattern": "reduced-function-word",
                "fragment": "for your",
                "sounds_like": "/fə jə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "„for your” se poate reduce la /fə jə/, două silabe foarte scurte înainte de „holidays”.",
            },
        ],
    },
    {
        "text": "I saw it on the news this morning.",
        "translation_ro": "Am văzut la știri azi-dimineață.",
        "topic": "small-talk",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "intrusive-r",
                "fragment": "saw it",
                "sounds_like": "/sɔːr ɪt/",
                "ro_approximation": "so-rit",
                "expected_from_level": "natural",
                "explanation_ro": "Mulți vorbitori britanici adaugă un „r” nescris între „saw” și „it”, pentru a lega vocalele.",
            },
            {
                "pattern": "linking",
                "fragment": "it on",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„it‿on” se leagă de obicei; în multe accente britanice /t/ poate deveni aici o oprire glotală.",
            },
        ],
    },
    # -------------------------------------------------------------- fast-british
    {
        "text": "Do you know what I mean?",
        "translation_ro": "Înțelegi ce vreau să zic?",
        "topic": "fast-british",
        "difficulty": 4,
        "patterns": [
            {
                "pattern": "fast-phrase",
                "fragment": "Do you know what I mean",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "fast",
                "explanation_ro": "Expresie de umplutură spusă adesea foarte repede, ca un singur bloc; se recunoaște mai ușor după ritm decât după cuvinte.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "what I",
                "sounds_like": "/wɒʔ aɪ/",
                "ro_approximation": "uo' ai",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „what” poate deveni o oprire glotală înaintea vocalei din „I”.",
            },
        ],
    },
    {
        "text": "I don't know, to be honest.",
        "translation_ro": "Nu știu, sincer.",
        "topic": "fast-british",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "I don't know",
                "sounds_like": "I dunno",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea informală, „I don't know” se reduce des la „I dunno”, cu /t/ și /d/ estompate.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "În „to be honest”, „to” are de obicei forma slabă /tə/.",
            },
        ],
    },
    {
        "text": "I'm not being funny, but that's a bit much.",
        "translation_ro": "Nu vreau să par nepoliticos, dar e cam mult.",
        "topic": "fast-british",
        "difficulty": 5,
        "patterns": [
            {
                "pattern": "fast-phrase",
                "fragment": "I'm not being funny",
                "sounds_like": "",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "Formulă britanică spusă de obicei dintr-o suflare înaintea unei critici; nu are legătură cu umorul.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "not being",
                "sounds_like": "/nɒʔ ˈbiːɪŋ/",
                "ro_approximation": "no' biing",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „not” poate deveni o oprire glotală înaintea lui /b/.",
            },
        ],
    },
    {
        "text": "Let me know if you need anything.",
        "translation_ro": "Spune-mi dacă ai nevoie de ceva.",
        "topic": "fast-british",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "everyday-reduction",
                "fragment": "Let me",
                "sounds_like": "lemme",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea informală, „let me” se reduce adesea la „lemme”, fără /t/.",
            },
            {
                "pattern": "linking",
                "fragment": "need anything",
                "sounds_like": "",
                "ro_approximation": "ni-denifing",
                "expected_from_level": "clear",
                "explanation_ro": "/d/ din „need” se leagă de obicei de vocala din „anything”, fără pauză.",
            },
        ],
    },
    {
        "text": "I haven't got a clue, mate.",
        "translation_ro": "N-am nici cea mai vagă idee, frate.",
        "topic": "fast-british",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "haven't",
                "sounds_like": "/ˈhævn̩(t)/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„have not” se contractă de obicei la „haven't”; înainte de „got”, /t/ final adesea abia se aude.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "got a",
                "sounds_like": "/ɡɒʔ ə/",
                "ro_approximation": "go'a",
                "expected_from_level": "natural",
                "explanation_ro": "În multe accente britanice, /t/ din „got” poate deveni o oprire glotală înaintea vocalei din „a”.",
            },
        ],
    },
    {
        "text": "What do you reckon?",
        "translation_ro": "Tu ce zici?",
        "topic": "fast-british",
        "difficulty": 4,
        "patterns": [
            {
                "pattern": "fast-phrase",
                "fragment": "What do you",
                "sounds_like": "/wɒʔ djə/",
                "ro_approximation": "",
                "expected_from_level": "fast",
                "explanation_ro": "În vorbirea rapidă, „what do you” se poate comprima în două silabe scurte, iar „reckon” rămâne cuvântul clar.",
            },
        ],
    },
    {
        "text": "I like the idea of it, to be fair.",
        "translation_ro": "Îmi place ideea, ca să fiu corect.",
        "topic": "fast-british",
        "difficulty": 4,
        "patterns": [
            {
                "pattern": "intrusive-r",
                "fragment": "idea of it",
                "sounds_like": "/aɪˈdɪər əv ɪt/",
                "ro_approximation": "aidia-răv it",
                "expected_from_level": "natural",
                "explanation_ro": "Mulți vorbitori britanici inserează un „r” nescris între „idea” și „of”, pentru a lega vocalele.",
            },
            {
                "pattern": "fast-phrase",
                "fragment": "to be fair",
                "sounds_like": "/tə bi feə/",
                "ro_approximation": "",
                "expected_from_level": "natural",
                "explanation_ro": "Expresie de umplutură foarte frecventă, spusă de obicei rapid la final, cu „to” în forma slabă /tə/.",
            },
        ],
    },
    {
        "text": "Cheers, mate, see you in a bit.",
        "translation_ro": "Mersi, frate, ne vedem mai încolo.",
        "topic": "fast-british",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "fast-phrase",
                "fragment": "see you in a bit",
                "sounds_like": "/siː jə ɪn ə bɪʔ/",
                "ro_approximation": "si-iă-nă-bi'",
                "expected_from_level": "natural",
                "explanation_ro": "Salut de despărțire spus de obicei ca un bloc, cu /t/ final adesea înlocuit de o oprire glotală.",
            },
        ],
    },
    {
        "text": "It's all about law and order these days.",
        "translation_ro": "Acum totul e despre ordine publică.",
        "topic": "fast-british",
        "difficulty": 4,
        "patterns": [
            {
                "pattern": "intrusive-r",
                "fragment": "law and order",
                "sounds_like": "/lɔːr ən ˈɔːdə/",
                "ro_approximation": "lo-răn odă",
                "expected_from_level": "natural",
                "explanation_ro": "Mulți vorbitori britanici inserează un „r” nescris între „law” și „and”, pentru a lega vocalele.",
            },
            {
                "pattern": "weak-form",
                "fragment": "and",
                "sounds_like": "/ən/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„and” neaccentuat are de obicei forma slabă /ən/, un sunet scurt între „law” și „order”.",
            },
        ],
    },
    # ------------------------------------------------------------ added (pilot)
    {
        "text": "We've run out of milk, could you grab some on the way home?",
        "translation_ro": "Am rămas fără lapte, poți să iei în drum spre casă?",
        "topic": "everyday",
        "difficulty": 3,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "We've",
                "sounds_like": "/wiːv/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„we have” se contractă de obicei la „we've”, iar /v/ final e scurt și ușor de ratat.",
            },
            {
                "pattern": "linking",
                "fragment": "run out of",
                "sounds_like": "/rʌn aʊt əv/",
                "ro_approximation": "ra-nau-tăv",
                "expected_from_level": "clear",
                "explanation_ro": "Consoanele finale se leagă de obicei de vocalele următoare, iar „of” are forma slabă /əv/: „run‿out‿of”.",
            },
            {
                "pattern": "assimilation",
                "fragment": "could you",
                "sounds_like": "/kʊdʒu/",
                "ro_approximation": "cugiu",
                "expected_from_level": "natural",
                "explanation_ro": "În vorbirea curentă, „d” + „you” se contopesc adesea în /dʒ/, iar „could you” sună ca un singur cuvânt.",
            },
        ],
    },
    {
        "text": "I couldn't make it to the meeting this morning.",
        "translation_ro": "N-am putut ajunge la ședință azi-dimineață.",
        "topic": "work",
        "difficulty": 2,
        "patterns": [
            {
                "pattern": "contraction",
                "fragment": "couldn't",
                "sounds_like": "/ˈkʊdn̩(t)/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„could not” se contractă de obicei la „couldn't”; înaintea unei consoane, /t/ final adesea abia se aude.",
            },
            {
                "pattern": "glottal-t",
                "fragment": "make it",
                "sounds_like": "/meɪk ɪʔ/",
                "ro_approximation": "mei-chi'",
                "expected_from_level": "natural",
                "explanation_ro": "„make‿it” se leagă de obicei, iar în multe accente britanice /t/ din „it” poate deveni o oprire glotală înainte de „to”.",
            },
            {
                "pattern": "weak-form",
                "fragment": "to",
                "sounds_like": "/tə/",
                "ro_approximation": "",
                "expected_from_level": "clear",
                "explanation_ro": "„to” neaccentuat are de obicei forma slabă /tə/ și se pierde ușor înainte de „the meeting”.",
            },
        ],
    },
]


# Pilot corpus: a compact, balanced subset recorded first at all three levels.
PILOT: list[str] = [
    # would you / did you / could you (yod coalescence) + weak "to", linking
    "Would you like me to pick you up after work?",
    "Did you get a chance to look at it?",
    "Could you cover my shift on Saturday?",
    "We've run out of milk, could you grab some on the way home?",
    # weak "was", "have", "can"; everyday reductions (gonna)
    "I was going to give you a ring later.",
    "Have you got a minute?",
    "You could have told me earlier.",
    "Can you put the kettle on?",
    "Can I pay by card?",
    # weak "to" and "of" (transport, healthcare)
    "Does this bus go to the station?",
    "Take two of these twice a day after food.",
    # linking R and schwa
    "Stand clear of the closing doors, please.",
    "Are you after anything in particular?",
    # contractions: I'll, I'd, didn't, couldn't
    "I'll sort it out later.",
    "I'd like to book an appointment with a GP.",
    "I didn't realise you were coming.",
    "I couldn't make it to the meeting this morning.",
    # elision and place assimilation
    "The next train is delayed by ten minutes.",
    "Mind the gap.",
    "That's ten pounds fifty, please.",
    "I'm just going to nip to the shop.",
    # glottal T
    "Sorry, I'm running a bit late this morning.",
    "I might pop in on the way home.",
    # phone calls
    "Can I just take your name, please?",
    "Can you hold on for a second?",
    # healthcare question with h-less weak "have"
    "How long have you had the cough?",
    # everyday British conversational phrases / short questions
    "Do you fancy grabbing a coffee?",
    "Shall we head off?",
]


# Short set for comparing TTS voices; each line isolates one phenomenon.
AUDITION_PHRASES: list[dict] = [
    {"text": "Does this bus go to the station?", "focus": "weak 'to'"},
    {"text": "Take two of these twice a day after food.", "focus": "weak 'of'"},
    {"text": "Would you like me to pick you up after work?", "focus": "'would you' coalescence"},
    {"text": "Could you turn the telly down a bit?", "focus": "'could you' coalescence"},
    {"text": "Did you have a good weekend?", "focus": "'did you' coalescence"},
    {"text": "Can you hold on for a second?", "focus": "linking (incl. linking R)"},
    {"text": "I didn't realise you were coming.", "focus": "contraction"},
    {"text": "The next train is delayed by ten minutes.", "focus": "elision"},
    {"text": "Have you got a minute?", "focus": "glottal T"},
    {"text": "My brother plays football on Sundays.", "focus": "plain control sentence"},
    {"text": "Are you alright?", "focus": "British conversational question"},
]
