# Generated by Django 5.2.5 on 2026-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='citat')),
                ('author_name', models.CharField(max_length=80, verbose_name='nume')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='locație')),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166, ex. RO, FR, GB.', max_length=2, verbose_name='cod țară')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='avatar')),
                ('active', models.BooleanField(default=True, verbose_name='activ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimoniale',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
