# Generated by Django 5.2.5 on 2026-09-21 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('daily', 'Ascultare zilnică'), ('topic', 'Temă'), ('pattern', 'Tipar'), ('personalized', 'Personalizat'), ('trial', 'Încercare gratuită')], max_length=20)),
                ('level', models.CharField(choices=[('clear', 'Engleză britanică'), ('natural', 'Engleză naturală'), ('fast', 'Engleză rapidă')], default='clear', max_length=10)),
                ('local_date', models.DateField(help_text='Data locală a utilizatorului la creare.')),
                ('target_count', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='listening.accent')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listening.speechpattern')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listening.topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesiune de exerciții',
                'verbose_name_plural': 'sesiuni de exerciții',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listening.listeningphrase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='practice.practicesession')),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_key', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(choices=[('clear', 'Engleză britanică'), ('natural', 'Engleză naturală'), ('fast', 'Engleză rapidă')], default='clear', max_length=10)),
                ('typed_answer', models.TextField(blank=True, verbose_name='răspuns')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('word_accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('listened_count', models.PositiveSmallIntegerField(default=0, verbose_name='ascultări')),
                ('replay_count', models.PositiveSmallIntegerField(default=0, verbose_name='reluări')),
                ('time_spent_ms', models.PositiveIntegerField(default=0, verbose_name='timp petrecut (ms)')),
                ('slowed_down', models.BooleanField(default=False, verbose_name='a redus viteza')),
                ('transcript_revealed', models.BooleanField(default=False, verbose_name='transcriere afișată')),
                ('revealed_before_check', models.BooleanField(default=False, verbose_name='transcriere înainte de verificare')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='listening.audiovariant')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='listening.listeningphrase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('session_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.sessionitem')),
            ],
            options={
                'verbose_name': 'încercare',
                'verbose_name_plural': 'încercări',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_word', models.CharField(blank=True, max_length=80)),
                ('typed_word', models.CharField(blank=True, max_length=80)),
                ('mistake_type', models.CharField(choices=[('missing', 'Cuvânt lipsă'), ('incorrect', 'Cuvânt greșit'), ('extra', 'Cuvânt în plus'), ('order', 'Ordine greșită'), ('contraction', 'Formă contrasă'), ('spelling', 'Ortografie UK/US')], max_length=20)),
                ('severity', models.FloatField(default=1.0)),
                ('speech_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='listening.speechpattern')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='practice.listeningattempt')),
            ],
            options={
                'verbose_name': 'greșeală',
                'verbose_name_plural': 'greșeli',
                'ordering': ['attempt', 'position'],
                'indexes': [models.Index(fields=['speech_pattern', 'mistake_type'], name='practice_at_speech__7a6081_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'kind', 'local_date'], name='practice_pr_user_id_62747f_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicesession',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('anon_key', ''), _negated=True), _connector='OR'), name='session_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_session_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'phrase'), name='unique_session_phrase'),
        ),
        migrations.AddIndex(
            model_name='listeningattempt',
            index=models.Index(fields=['user', 'completed', 'completed_at'], name='practice_li_user_id_23f568_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningattempt',
            index=models.Index(fields=['anon_key', 'completed'], name='practice_li_anon_ke_e55bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningattempt',
            index=models.Index(fields=['user', 'phrase'], name='practice_li_user_id_79fe7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='listeningattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__lte', 100), _connector='OR'), name='attempt_score_range'),
        ),
        migrations.AddConstraint(
            model_name='listeningattempt',
            constraint=models.CheckConstraint(condition=models.Q(('word_accuracy__isnull', True), ('word_accuracy__lte', 100), _connector='OR'), name='attempt_accuracy_range'),
        ),
        migrations.AddConstraint(
            model_name='listeningattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('session_item__isnull', False)), fields=('session_item',), name='one_attempt_per_session_item'),
        ),
    ]
