# Generated by Django 5.2.5 on 2026-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='voice',
            field=models.CharField(choices=[('marin', 'Marin'), ('ballad', 'Ballad'), ('cedar', 'Cedar')], default='marin', max_length=20),
        ),
    ]
