# Generated by Django 5.2.5 on 2026-09-21 10:18

import apps.listening.models
import apps.listening.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300, unique=True, verbose_name='text (EN)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('translation_ro', models.CharField(blank=True, max_length=300, verbose_name='traducere (RO)')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1 · Ușor'), (2, '2 · Accesibil'), (3, '3 · Mediu'), (4, '4 · Dificil'), (5, '5 · Foarte dificil')], default=2, verbose_name='dificultate')),
                ('active', models.BooleanField(default=True, verbose_name='activ')),
            ],
            options={
                'verbose_name': 'frază',
                'verbose_name_plural': 'fraze',
                'ordering': ['topic__order', 'difficulty', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SpeechPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_ro', models.CharField(max_length=80, verbose_name='nume (RO)')),
                ('name_en', models.CharField(max_length=80, verbose_name='nume (EN)')),
                ('description_ro', models.TextField(verbose_name='descriere')),
                ('group', models.CharField(choices=[('weak_forms', 'Forme slabe'), ('linking', 'Sunete legate între cuvinte'), ('frequent_phrases', 'Expresii folosite frecvent'), ('accents', 'Accente britanice')], max_length=20, verbose_name='grup')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
            ],
            options={
                'verbose_name': 'tipar de vorbire',
                'verbose_name_plural': 'tipare de vorbire',
                'ordering': ['order', 'name_ro'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_ro', models.CharField(max_length=80, verbose_name='nume (RO)')),
                ('name_en', models.CharField(max_length=80, verbose_name='nume (EN)')),
                ('description_ro', models.CharField(blank=True, max_length=200, verbose_name='descriere')),
                ('icon', models.CharField(default='chat', max_length=40, verbose_name='iconiță')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
                ('active', models.BooleanField(default=True, verbose_name='activ')),
            ],
            options={
                'verbose_name': 'temă',
                'verbose_name_plural': 'teme',
                'ordering': ['order', 'name_ro'],
            },
        ),
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name_ro', models.CharField(max_length=80, verbose_name='nume (RO)')),
                ('name_en', models.CharField(max_length=80, verbose_name='nume (EN)')),
                ('description_ro', models.TextField(blank=True, verbose_name='descriere')),
                ('tts_supported', models.BooleanField(default=False, help_text='Bifează doar dacă vocea sintetizată redă accentul fiabil. Altfel, folosește înregistrări umane încărcate manual.', verbose_name='suportat de sinteza vocală')),
                ('tts_instructions', models.CharField(blank=True, help_text='Descrierea accentului trimisă providerului TTS.', max_length=300, verbose_name='instrucțiuni TTS')),
                ('is_default', models.BooleanField(default=False, verbose_name='implicit')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
                ('active', models.BooleanField(default=True, verbose_name='activ')),
            ],
            options={
                'verbose_name': 'accent',
                'verbose_name_plural': 'accente',
                'ordering': ['order', 'name_ro'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_accent')],
            },
        ),
        migrations.CreateModel(
            name='PhrasePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.CharField(help_text='Cuvintele exacte din frază (ex. „would you”).', max_length=120, verbose_name='fragment')),
                ('start_token', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('end_token', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('sounds_like', models.CharField(blank=True, help_text='Opțional: IPA sau formă uzuală (ex. /tə/).', max_length=80, verbose_name='sună ca')),
                ('explanation_ro', models.CharField(max_length=300, verbose_name='explicație (RO)')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_patterns', to='listening.listeningphrase')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrase_patterns', to='listening.speechpattern')),
            ],
            options={
                'verbose_name': 'tipar în frază',
                'verbose_name_plural': 'tipare în fraze',
                'ordering': ['phrase', 'start_token'],
            },
        ),
        migrations.AddField(
            model_name='listeningphrase',
            name='patterns',
            field=models.ManyToManyField(blank=True, related_name='phrases', through='listening.PhrasePattern', to='listening.speechpattern'),
        ),
        migrations.AddField(
            model_name='listeningphrase',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to='listening.topic', verbose_name='temă'),
        ),
        migrations.CreateModel(
            name='AudioVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('clear', 'Engleză britanică'), ('natural', 'Engleză naturală'), ('fast', 'Engleză rapidă')], max_length=10, verbose_name='nivel')),
                ('voice', models.CharField(max_length=60, verbose_name='voce')),
                ('audio_file', models.FileField(blank=True, upload_to=apps.listening.models.audio_upload_path, validators=[apps.listening.validators.validate_audio_file], verbose_name='fișier audio')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='durată (ms)')),
                ('provider', models.CharField(help_text='ex. openai, mock, human (înregistrare umană)', max_length=30, verbose_name='sursă')),
                ('cache_key', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('generation_settings', models.JSONField(blank=True, default=dict, help_text='Metadate specifice providerului (model, instrucțiuni, viteză).', verbose_name='setări generare')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generat la')),
                ('accent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_variants', to='listening.accent')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_variants', to='listening.listeningphrase')),
            ],
            options={
                'verbose_name': 'variantă audio',
                'verbose_name_plural': 'variante audio',
                'ordering': ['phrase', 'level'],
                'indexes': [models.Index(fields=['phrase', 'level', 'accent'], name='listening_a_phrase__63bd06_idx')],
                'constraints': [models.UniqueConstraint(fields=('phrase', 'level', 'accent', 'voice'), name='unique_audio_variant')],
            },
        ),
        migrations.AddConstraint(
            model_name='phrasepattern',
            constraint=models.UniqueConstraint(fields=('phrase', 'pattern', 'start_token'), name='unique_pattern_span'),
        ),
        migrations.AddConstraint(
            model_name='phrasepattern',
            constraint=models.CheckConstraint(condition=models.Q(('end_token__gte', models.F('start_token'))), name='pattern_span_ordered'),
        ),
        migrations.AddIndex(
            model_name='listeningphrase',
            index=models.Index(fields=['active', 'difficulty'], name='listening_l_active_7b09a5_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningphrase',
            index=models.Index(fields=['topic', 'active'], name='listening_l_topic_i_a22fb5_idx'),
        ),
    ]
