# Generated by Django 5.2.5 on 2026-09-21 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVariantPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification', models.CharField(choices=[('unverified', 'Neverificat (doar așteptat)'), ('present', 'Prezent în înregistrare'), ('absent', 'Absent din înregistrare')], default='unverified', max_length=12, verbose_name='verificare')),
                ('realisation', models.CharField(blank=True, help_text='Ce se aude efectiv în această înregistrare (ex. /ɡɒʔ ə/).', max_length=120, verbose_name='cum se aude aici')),
                ('explanation_override_ro', models.CharField(blank=True, help_text='Opțional. Descrie exact ce se aude aici; altfel se folosește explicația generală.', max_length=300, verbose_name='explicație pentru această înregistrare')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tipar verificat în audio',
                'verbose_name_plural': 'tipare verificate în audio',
                'ordering': ['audio_variant', 'phrase_pattern__start_token'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='audiovariant',
            name='unique_audio_variant',
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='duration_measured',
            field=models.BooleanField(default=False, help_text='Adevărat dacă durata a fost citită din fișier. Altfel e aproximativă; playerul din browser afișează durata exactă.', verbose_name='durată măsurată'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='engine_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='versiune motor TTS'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='instrucțiuni trimise'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='model',
            field=models.CharField(blank=True, max_length=60, verbose_name='model TTS'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='qa_notes',
            field=models.TextField(blank=True, verbose_name='note QA'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='qa_status',
            field=models.CharField(choices=[('pending', 'De verificat'), ('approved', 'Aprobat'), ('rejected', 'Respins')], db_index=True, default='pending', max_length=10, verbose_name='status QA'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verificat la'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='verificat de'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='viteză'),
        ),
        migrations.AddField(
            model_name='listeningphrase',
            name='in_pilot',
            field=models.BooleanField(db_index=True, default=False, help_text='Fraze folosite pentru QA audio înainte de generarea completă.', verbose_name='corpus pilot'),
        ),
        migrations.AddField(
            model_name='phrasepattern',
            name='expected_from_level',
            field=models.CharField(choices=[('clear', 'Engleză britanică'), ('natural', 'Engleză naturală'), ('fast', 'Engleză rapidă')], default='clear', help_text='Cel mai lent nivel la care fenomenul apare de obicei. Prezența reală se verifică pe fiecare variantă audio.', max_length=10, verbose_name='așteptat de la nivelul'),
        ),
        migrations.AddField(
            model_name='phrasepattern',
            name='ro_approximation',
            field=models.CharField(blank=True, help_text='Ex. „digiu”. Nu este transcriere fonetică; în UI apare etichetată ca atare.', max_length=80, verbose_name='aproximare pentru urechea românească'),
        ),
        migrations.AlterField(
            model_name='phrasepattern',
            name='explanation_ro',
            field=models.CharField(help_text='Tendința generală în vorbirea naturală, formulată prudent (poate / adesea).', max_length=300, verbose_name='explicație generală (RO)'),
        ),
        migrations.AlterField(
            model_name='phrasepattern',
            name='sounds_like',
            field=models.CharField(blank=True, help_text='IPA între /…/ (ex. /tə/) sau o formă informală consacrată (ex. gonna).', max_length=80, verbose_name='IPA / formă uzuală'),
        ),
        migrations.AddIndex(
            model_name='audiovariant',
            index=models.Index(fields=['phrase', 'level', 'accent', 'qa_status'], name='listening_a_phrase__30885b_idx'),
        ),
        migrations.AddField(
            model_name='audiovariantpattern',
            name='audio_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_checks', to='listening.audiovariant'),
        ),
        migrations.AddField(
            model_name='audiovariantpattern',
            name='phrase_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_checks', to='listening.phrasepattern'),
        ),
        migrations.AddField(
            model_name='audiovariantpattern',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='audiovariantpattern',
            constraint=models.UniqueConstraint(fields=('audio_variant', 'phrase_pattern'), name='unique_variant_pattern'),
        ),
    ]


def backfill(apps, schema_editor):
    """Keep every existing recording; record what we know about how it was generated."""
    AudioVariant = apps.get_model("listening", "AudioVariant")
    AudioVariantPattern = apps.get_model("listening", "AudioVariantPattern")
    PhrasePattern = apps.get_model("listening", "PhrasePattern")
    for variant in AudioVariant.objects.all().iterator():
        settings_json = variant.generation_settings or {}
        variant.model = settings_json.get("model", "")[:60]
        speed = settings_json.get("speed")
        variant.speed = float(speed) if isinstance(speed, (int, float)) else None
        variant.engine_version = "1"
        variant.duration_measured = variant.provider == "mock"  # mock WAVs have exact durations
        variant.save(
            update_fields=["model", "speed", "engine_version", "duration_measured"]
        )
        for pp in PhrasePattern.objects.filter(phrase_id=variant.phrase_id):
            AudioVariantPattern.objects.get_or_create(audio_variant=variant, phrase_pattern=pp)


Migration.operations.append(migrations.RunPython(backfill, migrations.RunPython.noop))
