# Generated by Django 5.2.5 on 2026-09-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_audio_qa_and_variant_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovariant',
            name='approval_source',
            field=models.CharField(blank=True, choices=[('automatic', 'Automat (auto-QA)'), ('human', 'Om (staff)')], help_text='Automat = auto-QA; om = staff. Gol = încă nicio decizie.', max_length=10, verbose_name='decizie luată de'),
        ),
        migrations.AddField(
            model_name='audiovariant',
            name='audio_sha256',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='audiovariantpattern',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='încredere (auto-QA)'),
        ),
        migrations.AddField(
            model_name='audiovariantpattern',
            name='source',
            field=models.CharField(blank=True, choices=[('automatic', 'Automat (auto-QA)'), ('human', 'Om (staff)')], max_length=10, verbose_name='verificat de'),
        ),
        migrations.AlterField(
            model_name='audiovariant',
            name='qa_status',
            field=models.CharField(choices=[('pending', 'Neverificat încă'), ('approved', 'Aprobat'), ('needs_review', 'De ascultat manual'), ('rejected', 'Respins')], db_index=True, default='pending', max_length=15, verbose_name='status QA'),
        ),
        migrations.CreateModel(
            name='AudioQAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('qa_version', models.CharField(max_length=20)),
                ('audio_sha256', models.CharField(max_length=64)),
                ('transcribe_model', models.CharField(blank=True, max_length=60)),
                ('evaluator_model', models.CharField(blank=True, max_length=60)),
                ('technical_pass', models.BooleanField(default=False)),
                ('transcript_pass', models.BooleanField(null=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_similarity', models.FloatField(null=True)),
                ('transcript_confidence', models.FloatField(null=True)),
                ('confidence_label', models.CharField(blank=True, max_length=10)),
                ('duration_pass', models.BooleanField(null=True)),
                ('accent_pass', models.BooleanField(null=True)),
                ('accent_label', models.CharField(blank=True, max_length=30)),
                ('delivery_pass', models.BooleanField(null=True)),
                ('phonetic_pass', models.BooleanField(null=True)),
                ('overall_score', models.PositiveSmallIntegerField(null=True)),
                ('decision', models.CharField(choices=[('approved', 'Aprobat automat'), ('needs_review', 'De ascultat manual'), ('rejected', 'Respins'), ('error', 'Eroare (se reia)')], max_length=15)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Rezumate mici (logprob, evaluator), nu răspunsuri brute.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_results', to='listening.audiovariant')),
            ],
            options={
                'verbose_name': 'rezultat auto-QA',
                'verbose_name_plural': 'rezultate auto-QA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audio_variant', '-created_at'], name='listening_a_audio_v_b63d46_idx')],
            },
        ),
    ]
